restructure multileadtype and remove big test file
resurfemg-org/ReSurfEMG pull request #283
Opened 2023-11-10 14:40 UTC by ElineOppersma

2023-11-10 15:55 UTC, rspwarnaarUT commented
def working_pipeline_exp(our_chosen_file): in helper_functions_legacy is the only function that is not moved yet. See the this file with my changes where I commented out all methods that are moved to their new locations.

2023-11-10 16:00 UTC, rspwarnaarUT requested changes
See helper_functions_legacy

2024-01-04 14:23 UTC, ElineOppersma commented
Last function also moved from the legacy helper_functions and removed the legacy file. 
Note: notebooks should start now with:
`sys.path.insert(0, '..')`
whereafter the required modules can be imported, for exmaple:
`from resurfemg.preprocessing import filtering`

2024-01-06 18:45 UTC, rspwarnaarUT requested changes
working_pipeline_pre_ml Moet nog naar pipelines, dan is ie goed :)

2024-01-06 18:45 UTC, rspwarnaarUT commented on resurfemg/helper_functions_legacy.py
> -
This function (working_pipeline_pre_ml) is not yet introduced in another submodule

2024-01-08 15:05 UTC, rspwarnaarUT approved these changes

2024-01-08 15:05 UTC, merged