added periodogram and welch method
resurfemg-org/ReSurfEMG pull request #316
Opened 2024-06-21 12:17 UTC by ElineOppersma

2024-06-21 12:39 UTC, ElineOppersma commented
#60

2024-06-21 14:05 UTC, rspwarnaarUT requested changes

2024-06-21 14:05 UTC, rspwarnaar commented on resurfemg/visualization/visualization.py
> +        plt.ylabel('PSD [V**2/Hz]')
Aren't most signals recorded in uV scale, rather than V? Maybe change default/allow for entering a signal unit?

2024-06-21 14:05 UTC, rspwarnaar commented on resurfemg/visualization/visualization.py
> +def show_psd_welch(sample, sample_rate, nperseg, axis_spec):
Standardise naming:
sample --> signal
sample_rate --> fs_emg
nperseg is rather unclear to me. Align with, e.g., baseline functions: t_window_s. This makes it clear it is the time window averaged over.

2024-06-21 14:05 UTC, rspwarnaar commented on resurfemg/visualization/visualization.py
> +        plt.ylim([0.5e-3, 1])
Are these limits chosen for a reason? It does not work well on my own data. You could consider 1) making it optional, 2) cutting it out all together and leaving it to the user to adapt the limits.

2024-06-21 14:05 UTC, rspwarnaarUT commented on resurfemg/visualization/visualization.py
> +    return f, Pxx_den
I am missing tests for the functions. The plotting will probably not change much over time, the signal analysis functions might. Assuring "sample", f and Pxx_den to be of the same length will assure the functions within are not broken.

2024-06-21 14:05 UTC, rspwarnaarUT commented on resurfemg/visualization/visualization.py
> +    """This function calculates the periodogram.
Most of the comments above, also apply to this function

2024-06-25 07:48 UTC, rspwarnaarUT approved these changes
Nice work!
One minor thing: You might consider deleting the "Logarithmic Scale" and "Linear Scale" from the titles. Doens't add much (people can see it from the axis) and makes the code more concise.

2024-06-25 08:11 UTC, merged